spring:
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://pro-robot-mysql:3306/dev_process_robot?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: sAdKjgiOsa@
#      #Oracle
#      driver-class-name: oracle.jdbc.OracleDriver
#      url: jdbc:oracle:thin:@localhost:1521:xe
#      username: root
#      password: 123456
#      #SQLServer
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://localhost:1433;DatabaseName=dev-robot
#      username: sa
#      password: 123456
#      #postgresql
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/dev-robot
#      username: postgres
#      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  jms:
    # 配置消息的类型，如果是true则表示为topic消息，如果为false表示Queue消息
    pub-sub-domain: true
  activemq:
#    user: root    # 连接用户名
#    password: keep   # 连接密码
##    broker-url: tcp://dev-activemq-server:61616 # 消息组件的连接主机信息
#    broker-url: tcp://127.0.0.1:61616 # 消息组件的连接主机信息
    user: admin    # 连接用户名
    password: admin   # 连接密码
    broker-url: tcp://pro-robot-activemq:61616 # 消息组件的连接主机信息
##多数据源的配置，需要引用robot-dynamic-datasource
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://123456:1433;DatabaseName=dev-robot
#      username: sa
#      password: 123456
#    slave2:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://123456:5432/dev-robot
#      username: postgres
#      password: 123456
sikulix:
  result:
    path: C:\robot-result
device:
  ip: http://192.168.0.100/ #告警设备ip