version: '2'
services:
  iot-admin:
    image: iot/iot-admin
    ports:
    - "8080:8080"
    environment:
    - spring.profiles.active=dev
  iot-api:
    image: iot/iot-api
    ports:
    - "8081:8081"
    environment:
    - spring.profiles.active=dev