spring:
  jms:
    # 配置消息的类型，如果是true则表示为topic消息，如果为false表示Queue消息
    pub-sub-domain: true
  activemq:
#    user: root    # 连接用户名
#    password: keep   # 连接密码
#    broker-url: tcp://dev-activemq-server:61616 # 消息组件的连接主机信息
    user: admin    # 连接用户名
    password: admin   # 连接密码
    broker-url: tcp://pro-robot-activemq:61616 # 消息组件的连接主机信息
#ftp相关的配置
ftp:
  ip: 10.101.58.193
  port: 2058
  username: ftpuser
  password: Ftp_2017
file:
  http:
    url: http://10.110.63.194:7000/
#ftp:
#  ip: 10.110.63.199
#  port: 21
#  username: weihu
#  password: admin@123

#  谷歌浏览器本地路径
googleChrome:
  path: C:\Users.process.\AppData\Local\Google\Chrome\Application\chrome.exe
#  工单平台登录地址
workOrder:
  loginPath: http://10.113.251.84:8081/ucas/login?service=http%3A%2F%2F10.113.251.84%3A9902%2Fuflow%2Fj_acegi_cas_security_check%3Bjsessionid%3DA902AAB9E451F833E01820620C6E0937%3Ft%3Dhttp%253A%252F%252F10.113.251.84%253A9902%252Fuflow%252FcentraOpt%252Findex.jsp%253Fiamcaspticket%253DLNoIqeLOsfDSXh%25252BtNqa%25252FSsA24%25252BBvknsSrmwBhg3%25252Fjedfj7fuWgLe%25252Bzr3vWSoH1docl7OilRtpGCf%25250AN%25252FKOHOo96DW2fZtgooW5D0PxoWXg4MLYOJlKBXtw00j0xTODvh1s%25252Fg9ut4A5lb2kMbzQHvnZqzUW%25250AzF0sCvAxiJGQbr1cjavbdRrLtIVytwpGxt%25252FLthXr2t0%25252BFi7l9jXU9Eq0Od3qCMefDkin%25252FKxS