# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8081
  connection-timeout: 5000ms
  servlet:
    context-path: /robot-agent

# mysql
spring:
  # 环境 dev|test|prod
  profiles:
    active: local
  messages:
    encoding: UTF-8
    basename: i18n/messages
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
