spring:
  jms:
    # 配置消息的类型，如果是true则表示为topic消息，如果为false表示Queue消息
    pub-sub-domain: true
  activemq:
#    user: root    # 连接用户名
#    password: keep   # 连接密码
#    broker-url: tcp://dev-activemq-server:61616 # 消息组件的连接主机信息
    user: admin    # 连接用户名
    password: admin   # 连接密码
    broker-url: tcp://pro-robot-activemq:61616 # 消息组件的连接主机信息