// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.HeartBeat.proto

package com.szzt.iot.common.netty.proto;

public final class IMHeartBeat {
  private IMHeartBeat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IMHeartBeatDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.HeartBeat.IMHeartBeatData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes channel_id = 1;</code>
     */
    boolean hasChannelId();
    /**
     * <code>required bytes channel_id = 1;</code>
     */
    com.google.protobuf.ByteString getChannelId();

    /**
     * <code>optional bytes msg_data = 2;</code>
     */
    boolean hasMsgData();
    /**
     * <code>optional bytes msg_data = 2;</code>
     */
    com.google.protobuf.ByteString getMsgData();
  }
  /**
   * Protobuf type {@code IM.HeartBeat.IMHeartBeatData}
   */
  public  static final class IMHeartBeatData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IM.HeartBeat.IMHeartBeatData)
      IMHeartBeatDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IMHeartBeatData.newBuilder() to construct.
    private IMHeartBeatData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IMHeartBeatData() {
      channelId_ = com.google.protobuf.ByteString.EMPTY;
      msgData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new IMHeartBeatData();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IMHeartBeatData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              channelId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msgData_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IMHeartBeat.internal_static_IM_HeartBeat_IMHeartBeatData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IMHeartBeat.internal_static_IM_HeartBeat_IMHeartBeatData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IMHeartBeatData.class, Builder.class);
    }

    private int bitField0_;
    public static final int CHANNEL_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString channelId_;
    /**
     * <code>required bytes channel_id = 1;</code>
     */
    public boolean hasChannelId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required bytes channel_id = 1;</code>
     */
    public com.google.protobuf.ByteString getChannelId() {
      return channelId_;
    }

    public static final int MSG_DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString msgData_;
    /**
     * <code>optional bytes msg_data = 2;</code>
     */
    public boolean hasMsgData() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes msg_data = 2;</code>
     */
    public com.google.protobuf.ByteString getMsgData() {
      return msgData_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasChannelId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, channelId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, msgData_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, channelId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, msgData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof IMHeartBeatData)) {
        return super.equals(obj);
      }
      IMHeartBeatData other = (IMHeartBeatData) obj;

      if (hasChannelId() != other.hasChannelId()) return false;
      if (hasChannelId()) {
        if (!getChannelId()
            .equals(other.getChannelId())) return false;
      }
      if (hasMsgData() != other.hasMsgData()) return false;
      if (hasMsgData()) {
        if (!getMsgData()
            .equals(other.getMsgData())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasChannelId()) {
        hash = (37 * hash) + CHANNEL_ID_FIELD_NUMBER;
        hash = (53 * hash) + getChannelId().hashCode();
      }
      if (hasMsgData()) {
        hash = (37 * hash) + MSG_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getMsgData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static IMHeartBeatData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMHeartBeatData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMHeartBeatData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMHeartBeatData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMHeartBeatData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMHeartBeatData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMHeartBeatData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IMHeartBeatData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static IMHeartBeatData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static IMHeartBeatData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static IMHeartBeatData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IMHeartBeatData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(IMHeartBeatData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IM.HeartBeat.IMHeartBeatData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.HeartBeat.IMHeartBeatData)
        IMHeartBeatDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IMHeartBeat.internal_static_IM_HeartBeat_IMHeartBeatData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IMHeartBeat.internal_static_IM_HeartBeat_IMHeartBeatData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IMHeartBeatData.class, Builder.class);
      }

      // Construct using com.szzt.iot.common.netty.proto.IMHeartBeat.IMHeartBeatData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        channelId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IMHeartBeat.internal_static_IM_HeartBeat_IMHeartBeatData_descriptor;
      }

      @Override
      public IMHeartBeatData getDefaultInstanceForType() {
        return IMHeartBeatData.getDefaultInstance();
      }

      @Override
      public IMHeartBeatData build() {
        IMHeartBeatData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public IMHeartBeatData buildPartial() {
        IMHeartBeatData result = new IMHeartBeatData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.channelId_ = channelId_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgData_ = msgData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IMHeartBeatData) {
          return mergeFrom((IMHeartBeatData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IMHeartBeatData other) {
        if (other == IMHeartBeatData.getDefaultInstance()) return this;
        if (other.hasChannelId()) {
          setChannelId(other.getChannelId());
        }
        if (other.hasMsgData()) {
          setMsgData(other.getMsgData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasChannelId()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        IMHeartBeatData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (IMHeartBeatData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString channelId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes channel_id = 1;</code>
       */
      public boolean hasChannelId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required bytes channel_id = 1;</code>
       */
      public com.google.protobuf.ByteString getChannelId() {
        return channelId_;
      }
      /**
       * <code>required bytes channel_id = 1;</code>
       */
      public Builder setChannelId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        channelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes channel_id = 1;</code>
       */
      public Builder clearChannelId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        channelId_ = getDefaultInstance().getChannelId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msgData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes msg_data = 2;</code>
       */
      public boolean hasMsgData() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes msg_data = 2;</code>
       */
      public com.google.protobuf.ByteString getMsgData() {
        return msgData_;
      }
      /**
       * <code>optional bytes msg_data = 2;</code>
       */
      public Builder setMsgData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes msg_data = 2;</code>
       */
      public Builder clearMsgData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgData_ = getDefaultInstance().getMsgData();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:IM.HeartBeat.IMHeartBeatData)
    }

    // @@protoc_insertion_point(class_scope:IM.HeartBeat.IMHeartBeatData)
    private static final IMHeartBeatData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IMHeartBeatData();
    }

    public static IMHeartBeatData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<IMHeartBeatData>
        PARSER = new com.google.protobuf.AbstractParser<IMHeartBeatData>() {
      @Override
      public IMHeartBeatData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMHeartBeatData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IMHeartBeatData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<IMHeartBeatData> getParserForType() {
      return PARSER;
    }

    @Override
    public IMHeartBeatData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IM_HeartBeat_IMHeartBeatData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IM_HeartBeat_IMHeartBeatData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022IM.HeartBeat.proto\022\014IM.HeartBeat\"7\n\017IM" +
      "HeartBeatData\022\022\n\nchannel_id\030\001 \002(\014\022\020\n\010msg" +
      "_data\030\002 \001(\014B(\n$com.szzt.iot.common." +
      "netty.protoH\003"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_IM_HeartBeat_IMHeartBeatData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IM_HeartBeat_IMHeartBeatData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IM_HeartBeat_IMHeartBeatData_descriptor,
        new String[] { "ChannelId", "MsgData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
